const h = {
     d: '<div>'
    ,in: '<input>'
    ,lb: '<label>'
    ,bt: '<button>'
    ,sp: '<select>'
    ,ce: '<button>'
    ,sn: '<span>'
    ,o: '<option>'
    ,p: '<p>'
}
const c = {
     md2: 'col-md-2 mb-2'
    ,md3: 'col-md-3 mb-3'
    ,md4: 'col-md-4 mb-4'
    ,row: 'row'
    ,close: 'close'
    ,card: 'card'
    ,fontBolder: 'font-weight-bolder'
    ,cardBody: 'card-body'
    ,spr: 'selectpicker'
    ,mdf: 'md-form form-sm'
    ,fcl: 'form-control'
    ,btnp: 'btn btn-primary'
    ,btns: 'btn btn-secondary'
    ,btnss: 'btn btn-success'
    ,btnd: 'btn btn-danger'
    ,btnw: 'btn btn-warning'
    ,btnw: 'btn btn-info'
}
